name: drkns-nominal-case

on:  [push]

jobs:

  drkns-check:
    runs-on: ubuntu-24.04
    env:
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DRKNS_S3_PATH: ${{ secrets.DRKNS_S3_PATH }}
    steps:
      - uses: actions/checkout@v7

      - uses: actions/cache@v5
        with:
          path: /home/runner/.local
          key: ${{ runner.os }}-${{ hashFiles('.github/workflows/main.yml') }}

      - uses: astral-sh/setup-uv@v10.0.1

      - run: uvx drkns check

  ## %DRKNS_GROUPS{}% ##

  ## %DRKNS_GROUP_TEMPLATE_BEGIN% ##

  %DRKNS_GROUP_NAME%:
    runs-on: ubuntu-24.04
    needs: [drkns-check%DRKNS_DEPENDENCY_GROUPS_NAMES?{, }%%DRKNS_DEPENDENCY_GROUPS_NAMES{, }%]
    env:
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DRKNS_S3_PATH: ${{ secrets.DRKNS_S3_PATH }}
    steps:
      - uses: actions/checkout@v7

      - uses: actions/cache@v5
        with:
          path: /home/runner/.local
          key: ${{ runner.os }}-${{ hashFiles('.github/workflows/main.yml') }}

      - uses: astral-sh/setup-uv@v10.0.1

      - run: uvx drkns sync in

      ## %DRKNS_GROUP_UNITS{}% ##

      ## %DRKNS_UNIT_TEMPLATE_BEGIN% ##

      - name: %DRKNS_UNIT_NAME%
        run: uvx drkns run --limit-output %DRKNS_UNIT_NAME%
        continue-on-error: true

      # sync out after every step to preserve execution steps in case
      # of interruption
      - run: uvx drkns sync out

      ## %DRKNS_UNIT_TEMPLATE_END% ##

  ## %DRKNS_GROUP_TEMPLATE_END% ##

  drkns-join:
    runs-on: ubuntu-24.04
    needs: [%DRKNS_ALL_GROUPS_NAMES{, }%]
    env:
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DRKNS_S3_PATH: ${{ secrets.DRKNS_S3_PATH }}
    steps:
      - uses: actions/checkout@v7

      - uses: actions/cache@v5
        with:
          path: /home/runner/.local/lib/python3.8
          key: ${{ runner.os }}-${{ hashFiles('.github/workflows/main.yml') }}

      - uses: astral-sh/setup-uv@v10.0.1

      - run: uvx drkns sync in

      - run: uvx drkns clean

      - run: uvx drkns sync out --delete

      - run: uvx drkns run --summary
