name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.13, 3.14]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python-version }}

      - name: Check python version 🐍
        run: python -c "import sys; print(sys.version)"

      - name: Install uv 🧱
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install dependencies 🏗
        run: |
          uv sync --python ${{ matrix.python-version }}

      - name: MyPy 🧐
        run: uv run mypy --install-types --non-interactive drkns

      - name: ruff 🧐
        run: uv run ruff check ./src

      - name: Test 🔍
        run: uv run pytest tests
